Repository GoodPlaSSU/GoodPlaSSU-Backend, pull requests merged in 2022-05, with the labels that each got.

#6 Feat: resolve #4 Create comment api
  app.js
  routes/comment.js
Labels: enhancement

#7 Hy develop board api
  app.js
  routes/board.js
  routes/post.js
Labels: enhancement

#10 Feat: resolve #9 Create ad api
  app.js
  routes/ad.js
Labels: enhancement

#11 Hy develop mypage api
  app.js
  routes/board.js
  routes/mypage.js
Labels: enhancement

#15 Hy duplicate get post api
  routes/board.js
  routes/mypage.js
Labels: duplicate

#17 Create cheer API
  app.js
  routes/board.js
  routes/cheer.js
Labels: enhancement

#20 Feat: #12 upload and delete image to cloudinary
  app.js
  package-lock.json
  package.json
  routes/board.js
Labels: enhancement

#23 Hy develop month point api
  app.js
  routes/monthPoint.js
Labels: enhancement

#26 Feat: CORS setting to connect with front
  app.js
  package-lock.json
  package.json
Labels: enhancement, help wanted, question

#30 Change: resolve #24 - Change login API...
  routes/login.js
Labels: duplicate, enhancement
